version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - NGINX_IMAGE_URI_TAG=$NGINX_IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build --file docker/nginx/Dockerfile -t $NGINX_IMAGE_URI_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $NGINX_IMAGE_URI_TAG
      - echo "[{\"name\":\"${CONTAINER_NAME}\",\"imageUri\":\"$NGINX_IMAGE_URI_TAG\"}]" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
